### ISSUE TITLE
Textual toolbar button

### ISSUE THREAD

**Issue by carlcs** [nystudio107/craft3-richvariables#2]
I wish the Rich Variables button was more consistent with all the other Redactor toolbar buttons which are text only and b/w.

**Comment by khalwat** [comment]
Yeah, I thought about that. Originally it was `Variables` but it seemed a bit verbose.

I will likely add an option to let people choose.

**Comment by khalwat** [comment]
Added it to the Craft 2.x plugin:

https://github.com/nystudio107/richvariables/releases/tag/1.0.2

Adding it to the Craft 3.x plugin now

**Comment by khalwat** [comment]
Feature implemented in 1.0.2:

https://github.com/nystudio107/craft3-richvariables/releases/tag/1.0.2
