### ISSUE TITLE
Richvariables for Plaintext Fields

### ISSUE THREAD

**Issue by wedot** [nystudio107/craft3-richvariables#24]
I'd link to use the Plugin for variables i use in a plaintext field. If i add `{globalset:8874:currentYear}﻿`to the plaintext i get the output `{globalset:8874:currentYear}`.

Is it planed to add this one?

**Comment by khalwat** [comment]
Unfortunately, plain text fields in Craft currently don't support Reference Tags.

**Comment by alexanderloewe** [comment]
Is there no way to add that one? I could use the replace filter for it, but that is a bit of a hack.

**Comment by khalwat** [comment]
It'd really need to be something they add to Craft core for it to work as you'd likely be expecting, I think.
