### ISSUE TITLE
Version 1.0.30 seems broken

### ISSUE THREAD

**Issue by nstcactus** [nystudio107/craft3-richvariables#39]
When running a site with the latest version of the plugin, I get the following error:

```
Not instantiable – yii\di\NotInstantiableException
Failed to instantiate component or class "nystudio107\pluginvite\services\VitePluginService".
↵
Caused by: ReflectionException
Class nystudio107\pluginvite\services\VitePluginService does not exist

in /var/www/html/craft/vendor/yiisoft/yii2/di/Container.php at line 507
```

If I downgrade to 1.0.29, it works fine. 

![image](https://user-images.githubusercontent.com/353843/150783958-34a052d5-27b9-4f71-a97c-7376130cb0e7.png)

**Comment by khalwat** [comment]
Addressed in:https://github.com/nystudio107/craft-richvariables/commit/c8321507d3bcea8a953e31428ccd7018976847a6

Released as 1.0.31 -> https://github.com/nystudio107/craft-richvariables/releases/tag/1.0.31
