### ISSUE TITLE
Composer requirements issue with Craft 4/Redactor

### ISSUE THREAD

**Issue by AndrewMac** [nystudio107/craft3-richvariables#43]
### Describe the bug
I can't install the version 4 beta due to an issue with composer requirements

### To reproduce
Steps to reproduce the behaviour:
1. Set composer "minimum-stability": "beta" 
2. Run composer require nystudio107/craft-richvariables:^4.0.0-beta.2
3. Get the following error:

Please note, by the way, that I believe Redactor 3 is now in beta
```
Problem 1
    - Root composer.json requires nystudio107/craft-richvariables ^4.0.0-beta.2 -> satisfiable by nystudio107/craft-richvariables[4.0.0-beta.2].
    - nystudio107/craft-richvariables 4.0.0-beta.2 requires craftcms/redactor 3.0.x-dev as 2.8.8 -> found craftcms/redactor[3.0.x-dev] but it does not match your minimum-stability.
```

### Expected behaviour
Composer installs the package ;-)

### Versions
- Plugin version: 4.0.0-beta.2
- Craft version: 4.0.0-beta.3

**Comment by khalwat** [comment]
Addressed in: Rich Variables 4.0.0-beta.3: https://github.com/nystudio107/craft-richvariables/releases/tag/4.0.0-beta.3
