### ISSUE TITLE
Calling unknown method: craft\models\FieldLayout::getFields()

### ISSUE THREAD

**Issue by padmedia** [nystudio107/craft3-richvariables#45]
Hi,

I'm running Craft CMS 4.2.0.2 with Rich Variables 4.0.0-beta.3 and Redactor 3.0.2.

Redactor fields won't load in CP.

I'm receiving a JS error "Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 5 of the JSON data"

The action being called is: 'actions/rich-variables&site=default' - Which returns a 500 error due to PHP error "Calling unknown method: craft\models\FieldLayout::getFields()".

Looks like on controllers/DefaultController.php on line 76, the plugin is using: 

`$fieldLayoutFields = $layout->getFields();`

I think it should be

`$fieldLayoutFields = $layout->getCustomFields();`

**Comment by khalwat** [comment]
Addressed via: https://github.com/nystudio107/craft-richvariables/commit/50da312ec24ae47b2fd1910471a8d0c9f18d158c

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-richvariables": "dev-develop-v4 as 4.0.0”,
```
Then do a `composer clear-cache && composer update`

**Comment by padmedia** [comment]
Thanks @khalwat for such a speedy response - That works perfectly, thank you.

**Comment by khalwat** [comment]
I will send out the release version shortly. Thank you for your excellent report
