### ISSUE TITLE
Rich Variables in plain text fields

### ISSUE THREAD

**Issue by alexanderloewe** [nystudio107/craft3-richvariables#50]
We use Rich Variables in some projects, now I get the question again and again, if it would be possible to use the variables in text fields, which are not redactor fields, but in plain text fields.

I would find this a good addition

**Comment by khalwat** [comment]
Unfortunately, that's not possible, because there is no UI available to plain text fields.

What you can do, though, is create a Redactor config that doesn't allow any styling at all except for Rich Variables, and use that in place of a plain text field. Rich Variables will work with that.
