### ISSUE TITLE
Setting variable values as the result of a GraphQL or rest query

### ISSUE THREAD

**Issue by dlindberg** [nystudio107/craft3-richvariables#6]
Is there an optimized method for updating variables as the result of a GraphQL or Rest query? I could see a way to do this using cron and a shell script, but it seems like there is probably a better way.

A rough example use case, the Census rest API provides population estimates. It would be helpful for those variables to automatically update based on Census updates on a page that shows the population for a state along with some other data points.

**Comment by khalwat** [comment]
So this really wouldn't have a whole lot to do with the Rich Variables plugin, in that all it does is pull from Craft Globals.

So you'd need to work out a way to update Globals with GraphQL, which I assume would be possible.

It's definitely doable.
